### ISSUE TITLE
[Bug]: [Hunter] Pet can sometimes be treated as alive, even when dead

### ISSUE THREAD

**Issue by lab1702** [herotc/hero-rotation#1023]
### What version of HeroRotation are you using?

10.2.0.32

### What version of HeroLib are you using?

10.2.0.17

### What version of HeroDBC are you using?

10.2.0.04

### What is the issue?

The most recent change to hunter pet status detection seems to have made things worse. When the pet is dead, I've had it show regular abilities as if the pet was alive, or the pet mend suggestion. Will see if there are specific sequences of events that always replicates this.

### Icon Behavior

Icon does NOT disappear

**Comment by Cilraaz** [comment]
It looks like it was possible for the pet's GUID in the Hunter table to be set to Hati's GUID, rather than your primary pet's GUID. I've made a change to delay the setting of pet status and GUID by 1 second (from completion of the cast) when casting Revive Pet. This change is in commit https://github.com/herotc/hero-rotation/commit/a3e9127cac6d80ba1f2f941b1a95ef240e3e94a2

Please let me know if this fixes your issue or if it continues to occur.

**Comment by lab1702** [comment]
Couple hours of testing in dungeon, outdoors and tank dummy, did not break at all. The old problem of logging out mounted is also still fixed.

**Comment by lab1702** [comment]
Spoke a tiny bit too soon.. had it think pet was summoned when it wasn't after a death in an instance.

**Comment by Cilraaz** [comment]
Your death or the pet's death?

**Comment by lab1702** [comment]
That time it was just my death.

**Comment by Cilraaz** [comment]
I made another tweak to try to catch the edge cases. This is in commit https://github.com/herotc/hero-rotation/commit/feb36cf3f426d80072e93b5efe28b8dc80fa15ef

**Comment by lab1702** [comment]
I think this last fix took care of the last issue, have not had it happen since last update in instances or outside.

**Comment by Cilraaz** [comment]
Great! I'm going to close the issue, then. Please let us know if you run into any other issues.
