### ISSUE TITLE
[Bug]: [Enhancement] Target Count Issue When Out of Range

### ISSUE THREAD

**Issue by nechyu** [herotc/hero-rotation#1040]
### What feature would you like to have added?

There's a problem with the shaman switching between AOE and ST mode. When AOE mode is on, when we move away from the target we get a POOL icon. And if you switch to ST mode, it will show rotation and is coloured red as it is far away from the target. This is one problem. 
The second problem in a quick change of abilities after the PWave lines if anything these are interested in 
[Hero Rotation] primordial_wave main 24 
[Hero Rotation] elemental_blast single 24 
[Hero Rotation] lightning_bolt single 20 
This is the sequence the addon often recommends. Sometimes hangs on elemental_blast. If you look at the rotation, elemental_blast only at the beginning of the rotation should be used, and in a long battle only this sequence should go like this.
[Hero Rotation] primordial_wave main 24 
[Hero Rotation] lightning_bolt single 20 

Fix these two things please. Happy New Year to you guys. Thanks for your addon.

**Comment by Cilraaz** [comment]
The first issue should be fixed in commit https://github.com/herotc/hero-rotation/commit/725f90ec16914f87af6e66064f635dd2c65e5790

The second issue should be fixed in commit https://github.com/herotc/hero-rotation/commit/129cd8fb71b71e4c7af5015a0f41d09cd08f0523

Unfortunately, the servers are currently down in my region and I can't copy my shaman to the PTR, so the changes are untested. I'll test them when the servers come back up.

**Comment by Cilraaz** [comment]
I made a couple more changes and fixed a small bug. The profile should work as expected now.
