### ISSUE TITLE
[Bug]: Outlaw rouge audacity/rtb/optimization

### ISSUE THREAD

**Issue by frydalici** [herotc/hero-rotation#1043]
### What version of HeroRotation are you using?

10.2.5.04

### What version of HeroLib are you using?

10.2.5.01

### What version of HeroDBC are you using?

10.2.5.01

### What is the issue?

New rule for ER/KiR builds: 
Consume Opportunity procs at 3 or fewer CPs if Broadside is not active.
Consume Opportunity procs at 0-1 CP if Broadside is active.
Consume Opportunity procs at any CP if at 6 Fan the Hammer stacks (if you don't have to finish).

Addon suggesting Roll the bones in subterfuge windows where loaded dice and a 1 roll had more than enough seconds left for Roll the bones to be used after the subterfuge window, (the addon also did this before the 10.2.5 wow patch)

Audacity proc shows as Sinister Strike icon, when it (should?) show as Ambush.

 

### Icon Behavior

None

**Comment by Seny951** [comment]
The latest Opportunity proc rules have been implemented for awhile, I've  rechecked the logic and it appears to be working correctly.

This is the SimC APL Condition for RtB:
_roll_the_bones,if=variable.rtb_reroll|rtb_buffs=0|rtb_buffs.max_remains<=2&set_bonus.tier31_4pc|rtb_buffs.max_remains<=7&(cooldown.shadow_dance.ready|cooldown.vanish.ready)_

the key conditions here being which would cause a reroll in a stealth window are:
_rtb_buffs.max_remains<=2&set_bonus.tier31_4pc_
This makes sure you don't lose a buff, in your situation with a 1 roll & loaded Dice, firstly this on it's own warrants a reroll for 3 buffs however the most important aspect is using the tier 4 set bonus to keep your existing buff.
 
The second part:
_rtb_buffs.max_remains<=7&(cooldown.shadow_dance.ready|cooldown.vanish.ready)_
As you said there was plenty of time left I suspect this is the part that's causing it as it's trying to make sure RtB is refreshed before going into the next stealth window which if you're already in the Vanish window and Dance comes up it'll want you to go straight into it with a fresh roll. I could potentially add in an additional condition here to delay the reroll until just before stealth is over but i will need to do some testing in game as this will be an APL deviation.

The SS suggestion with Audacity is intended there's even a note in game for Outlaw on Initialise:
![image](https://github.com/herotc/hero-rotation/assets/19662794/cce125b6-423d-4106-877c-bc9fed1df312)

The reason for this is there is a bug with SS when it gets changed automatically to ambush by an audacity proc. Pressing the SS keybind in this case can cause Ambush to triple hit (instead of double). This suggestion is to make it clear you should be pressing the SS procced version of ambush rather than a regular ambush keybind.

**Comment by frydalici** [comment]
thanks for clearing things up, yea the rtb in subterfuge def feels bad, but it might be a dps increase to do so and therefore the addon is telling you to do it, allthough it feels terribly bad  :z it didnt make u use rtb in subterfuge before 10.2.5, but maybe the apl changed?

**Comment by Seny951** [comment]
There was a condition put in which wasn't in the APL to explicitly stop it rerolling during a stealth window.  The APL itself never actually cared or blocked rerolling in stealth windows.

I took this back out because it could cause your buffs to fall off entirely which is a lot worse than rerolling in stealth.
i.e. if you missed your refresh before using vanish or dance so your buffs would fall off without it suggesting a reroll which would result in a wasted 4set & potentially a wasted Loaded Dice.

I look into improving the reroll suggestion and see about putting it back in.

Edit:
Actually I've just noticed something here:
variable.rtb_reroll is effectively much more advanced reroll conditions determining when you should reroll based on specific buffs and the number of buffs you have active. This condition doesn't care about stealth it just says (if you have a crap roll, reroll) I will put a stealth check alongside this and give it some testing

**Comment by frydalici** [comment]
Something else i've noticed is that the addon is telling you vanish/dance is off cd but i rewatched my vod where i pressed vanish into bte very fast, and the addon suggested vanish was off cd but in reality it had 0.3 sec left which made me use bte without subterfuge and made me hold vanish til bte was off cd again, is this intended too?

**Comment by Seny951** [comment]
No this is a bug, it's already fix and waiting in the pr along with the fix for the reroll in stealth issue.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
