### ISSUE TITLE
[Bug]:  WW switching distance bug

### ISSUE THREAD

**Issue by Dragonfo** [herotc/hero-rotation#1091]
### What version of HeroRotation are you using?

11.0.2.20

### What version of HeroLib are you using?

11.0.2.05

### What version of HeroDBC are you using?

11.0.2.02

### What is the issue?

The character stands right there as shown, and asks to switch to long-range targets. And can stop the rotation.
![image](https://github.com/user-attachments/assets/e7f77526-5337-4419-940d-abe5a9e3bc3a)

### Icon Behavior

None

**Comment by Cilraaz** [comment]
Where is the monk in this screenshot? The addon checks for targets within 8 yards of the player, not from the target (for melee, ranged classes are treated differently).

**Comment by Dragonfo** [comment]
I circled the monk on purpose, which was clearly shown. The addon recommends switching only to players so far away. If there are no players, the recommendation works correctly.

**Comment by Cilraaz** [comment]
Even after you point that out, the player is hardly visible in that screenshot. I'll assume that's what the red box is supposed to be surrounding.

The addon doesn't consider players. It only considers hostile targets (or targets that can be attacked, rather). For Monks, only the 8 yards surrounding the player are considered. This may be related to a range checking issue that has been occurring. I believe it's due to an undocumented change on Blizzard's end, whether an actual change or change in how addon code is loaded. I'm currently debugging that issue. Once I can fix that, we'll see if it fixes your issue.

**Comment by Cilraaz** [comment]
Update HeroDBC to version 11.0.2.03, and let me know if it's still a problem.

**Comment by Cilraaz** [comment]
No further reports. Assuming the change in HeroDBC 11.0.2.03 fixed the issue.
