### ISSUE TITLE
[UI] Add options to hide ALL Icons when no target or in a rested Zone outside of combat

### ISSUE THREAD

**Issue by Yakehira** [herotc/hero-rotation#128]
I don't think there is any need to show me Prowl or Stealth, while im "Rested" in a City, outside of combat or even if im out in the world without a target present.

**Comment by ghr74** [comment]
Hello,

you can hide the stealth reminder by unchecking "Stealth Reminder (OOC)" in the Rogue settings.
I'll put a toggle for Prowl on my To-Do.

**Comment by Cilraaz** [comment]
As per comment from issue #236:

Manually changed every spec to include Everyone.TargetIsValid() around opener spells (buffs, pet summons, etc will still be suggested with no target) to hide the icon when out of combat and no attackable target selected. Commit: https://github.com/herotc/hero-rotation/commit/9597a679308e591ade495766f70262a998ef24e8

Leaving this issue open, in case we want to add a toggle option or add this to HRGen itself instead of in each profile.
