### ISSUE TITLE
Offhand weapon errors when using fishing artifact as a rogue

### ISSUE THREAD

**Issue by MarcusGaius** [herotc/hero-rotation#193]
Hello, 

This is the error I keep getting when I use fishing artifact as a rogue. I have tested it on a paladin as well, no errors came up. 

Hope this helps. 

```
3375x HeroLib\Class\Unit\Player\Stat.lua:68: attempt to perform arithmetic on local 'offhandSpeed' (a nil value)
HeroLib\Class\Unit\Player\Stat.lua:68: in function `AttackPowerDamageMod'
HeroRotation_Rogue\Assassination.lua:108: in function `DamageFormula'
HeroLib\Class\Spell\Main.lua:60: in function `Damage'
HeroRotation_Rogue\Assassination.lua:437: in function `?'
HeroRotation\Main.lua:432: in function <HeroRotation\Main.lua:410>

Locals:
self = <table> {
 AttackPowerDamageMod = <function> defined @HeroLib\Class\Unit\Player\Stat.lua:61
 RunicPowerDeficitPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:362
 Race = <function> defined @HeroLib\Class\Unit\Player\Main.lua:34
 Insanityrain = <function> defined @HeroLib\Class\Unit\Player\Power.lua:599
 FocusLossOnCastEnd = <function> defined @HeroLib\Class\Unit\Player\Power.lua:219
 PainMax = <function> defined @HeroLib\Class\Unit\Player\Power.lua:668
 IsInVehicle = <function> defined @HeroLib\Class\Unit\Player\Main.lua:95
 EnergyDeficit = <function> defined @HeroLib\Class\Unit\Player\Power.lua:257
 Fury = <function> defined @HeroLib\Class\Unit\Player\Power.lua:645
 InstanceInfo = <function> defined @HeroLib\Class\Unit\Player\Instance.lua:68
 RageDeficit = <function> defined @HeroLib\Class\Unit\Player\Power.lua:139
 VersatilityDmgPct = <function> defined @HeroLib\Class\Unit\Player\Stat.lua:98
 ArcaneChargesDeficitPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:630
 MaelstromPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:510
 ArcaneCharges = <function> defined @HeroLib\Class\Unit\Player\Power.lua:615
 TimeToSht = <function> defined @HeroRotation_Rogue\Events.lua:316
 ActiveMitigationNeeded = <function> defined @HeroLib\Class\Unit\Player\Tank.lua:61
 SoulShardsDeficit = <function> defined @HeroLib\Class\Unit\Player\Power.lua:427
 EnergyPredictedWithRS = <function> defined @HeroRotation_Rogue\Events.lua:249
 IsInWhitelistedVehicle = <function> defined @HeroLib\Class\Unit\Player\Main.lua:124
 ShadowTechniques = <table> {
 }
 RSOffset = <table> {
 }
 PainDeficit = <function> defined @HeroLib\Class\Unit\Player\Power.lua:686
 AttackPower = <function> defined @HeroLib\Class\Unit\Player\Stat.lua:57
 ChiDeficit = <function> defined @HeroLib\Class\Unit\Player\Power.lua:544
 PainDeficitPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:690
 PrevOffGCD = <function> defined @HeroLib\Events\Prev_Spell.lua:162
 MasteryPct = <function> defined @HeroLib\Class\Unit\Player\Stat.lua:93
 InsanityPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:587
 ManaDeficitPercentageP = <function> defined @HeroLib\Class\Unit\Player\Power.lua:105
 FuryDeficit = <function> defined @HeroLib\Class\Unit\Player\Power.lua:656
 PrevGCD = <function> defined @HeroLib\Events\Prev_Spell.lua:140
 AstralPowerMax = <function> defined @HeroLib\Class\Unit\Player\Power.lua:435
 FocusDeficitPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:180
 EnergyRegenPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:265
 RunicPowerDeficit = <function> defined @HeroLib\Class\Unit\Player\Power.lua:358
 FuryPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:652
 Insanity = <function> defined @HeroLib\Class\Unit\Player\Power.lua:580
 EnergyTimeToMaxPredicted = <function> defined @HeroLib\Class\Unit\Player\Power.lua:305
 ArcaneChargesPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:622
 AstralPowerDeficitPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:458
 MaelstromDeficitPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:518
 FuryDeficitPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:660
 EnergyRegen = <function> defined @HeroLib\Class\Unit\Player\
```

**Comment by samueldruker** [comment]
I ran into a similar error today as an assassination rogue. I equipped random green non-weapon offhander (in order to learn the transmog appearance) and bugsack caught an error trying to get the off hand weapon speed. 

114x HeroLib\Class\Unit\Player\Stat.lua:68: attempt to perform arithmetic on local 'offhandSpeed' (a nil value)
HeroLib\Class\Unit\Player\Stat.lua:68: in function `AttackPowerDamageMod'
HeroRotation_Rogue\Assassination.lua:110: in function `DamageFormula'
HeroLib\Class\Spell\Main.lua:60: in function `Damage'
HeroRotation_Rogue\Assassination.lua:444: in function `?'
HeroRotation\Main.lua:432: in function <HeroRotation\Main.lua:410>

Locals:
self = <table> {
 AttackPowerDamageMod = <function> defined @HeroLib\Class\Unit\Player\Stat.lua:61
 RunicPowerDeficitPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:363
 Race = <function> defined @HeroLib\Class\Unit\Player\Main.lua:34
 Insanityrain = <function> defined @HeroLib\Class\Unit\Player\Power.lua:605
 FocusLossOnCastEnd = <function> defined @HeroLib\Class\Unit\Player\Power.lua:212
 PainMax = <function> defined @HeroLib\Class\Unit\Player\Power.lua:679
 IsInVehicle = <function> defined @HeroLib\Class\Unit\Player\Main.lua:92
 EnergyDeficit = <function> defined @HeroLib\Class\Unit\Player\Power.lua:249
 Fury = <function> defined @HeroLib\Class\Unit\Player\Power.lua:653
 InstanceInfo = <function> defined @HeroLib\Class\Unit\Player\Instance.lua:69
 RageDeficit = <function> defined @HeroLib\Class\Unit\Player\Power.lua:125
 VersatilityDmgPct = <function> defined @HeroLib\Class\Unit\Player\Stat.lua:98
 ArcaneChargesDeficitPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:637
 MaelstromPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:514
 ArcaneCharges = <function> defined @HeroLib\Class\Unit\Player\Power.lua:622
 TimeToSht = <function> defined @HeroRotation_Rogue\Events.lua:316
 ActiveMitigationNeeded = <function> defined @HeroLib\Class\Unit\Player\Tank.lua:57
 SoulShardsDeficit = <function> defined @HeroLib\Class\Unit\Player\Power.lua:432
 EnergyPredictedWithRS = <function> defined @HeroRotation_Rogue\Events.lua:249
 IsInWhitelistedVehicle = <function> defined @HeroLib\Class\Unit\Player\Main.lua:121
 ShadowTechniques = <table> {
 }
 RSOffset = <table> {
 }
 PainDeficit = <function> defined @HeroLib\Class\Unit\Player\Power.lua:694
 AttackPower = <function> defined @HeroLib\Class\Unit\Player\Stat.lua:57
 ChiDeficit = <function> defined @HeroLib\Class\Unit\Player\Power.lua:549
 PainDeficitPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:699
 PrevOffGCD = <function> defined @HeroLib\Events\Prev_Spell.lua:150
 MasteryPct = <function> defined @HeroLib\Class\Unit\Player\Stat.lua:93
 InsanityPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:590
 ManaDeficitPercentageP = <function> defined @HeroLib\Class\Unit\Player\Power.lua:99
 FuryDeficit = <function> defined @HeroLib\Class\Unit\Player\Power.lua:663
 PrevGCD = <function> defined @HeroLib\Events\Prev_Spell.lua:128
 AstralPowerMax = <function> defined @HeroLib\Class\Unit\Player\Power.lua:443
 FocusDeficitPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:166
 EnergyRegenPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:259
 RunicPowerDeficit = <function> defined @HeroLib\Class\Unit\Player\Power.lua:358
 FuryPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:658
 Insanity = <function> defined @HeroLib\Class\Unit\Player\Power.lua:585
 EnergyTimeToMaxPredicted = <function> defined @HeroLib\Class\Unit\Player\Power.lua:306
 ArcaneChargesPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:627
 AstralPowerDeficitPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:464
 MaelstromDeficitPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:524
 FuryDeficitPercentage = <function> defined @HeroLib\Class\Unit\Player\Power.lua:668
 EnergyRegen = <function> defined @HeroLib\Class\Unit\Player\P

**Comment by aethys256** [comment]
That's interesting, thanks for the report, I'll look into :)

**Comment by MarcusGaius** [comment]
Working fine with the latest update. Thank you.

**Comment by ghr74** [comment]
Should be mitigated as of https://github.com/herotc/hero-lib/commit/843dd6bfe6e5bf4d079721b13515cce738c593f5. Thanks for the report.
