### ISSUE TITLE
Frost Mage: Water Elemental suggested when elemental is out

### ISSUE THREAD

**Issue by Barleduq** [herotc/hero-rotation#197]
I logged in to my frost mage, who had the elemental out. The main icon is showing the Water Elemental icon. When I cast the spell again, it swapped to the Frostbolt icon. After 28 seconds (according to the stopwatch in game) it swapped back to the Elemental icon. 

I was standing in my class hall, not in combat. Swatter reported no lua errors. I installed from  HeroRotation-8.0.1.03.zip .

Thank you!

**Comment by Barleduq** [comment]
I downloaded off curseforge again, even tho the file name/number was the same. This time, I logged in and the arcane brilliance icon was up. I cast that spell, and the water elemental icon is up, and yes the water elemental is out. And, again, I cast the elemental spell again, it shifts to frostbolt, and back to the elemental icon. 

Should I be downloading from somewhere else? The 'last updated' filter shows HeroRotation last updated 8 hours ago. The file I mention above is the latest file listed on the page.

**Comment by ghr74** [comment]
These pages:
https://wow.curseforge.com/projects/herolib 
https://wow.curseforge.com/projects/herorotation 
have the alpha version downloads. Alternatively, if you use the twitch client for your addons, you can set the release channel of herolib and herorotation to Alpha there to get the newest updates almost instantly from github.

Gonna close this since this issue is fixed in the alpha release.
