### ISSUE TITLE
Frost DK Not Reliably Suggesting Empower Rune Weapon

### ISSUE THREAD

**Issue by DLSauron** [herotc/hero-rotation#248]
Empower Rune Weapon appears to only being suggested in the beginning combat and after a few attacks disappears from the suggested cool downs and never comes back. 

This also appears to prevent Pillar of Frost from being suggested as I have not seen Pillar of Frost as a suggested cool down ever unless Empower Rune Weapon is on cool down.

Current version: 8.0.1.06

**Comment by chrislopez24** [comment]
these are the two apl lines that calls erw

actions.cooldowns+=/empower_rune_weapon,if=cooldown.pillar_of_frost.ready&talent.breath_of_sindragosa.enabled&rune>=3&runic_power>60

actions.cooldowns+=/empower_rune_weapon,if=cooldown.pillar_of_frost.ready&!talent.breath_of_sindragosa.enabled&rune.time_to_5>gcd&runic_power.deficit>=10

the first one is called when you have bos talented, its suggesting erw when pof is ready to use, you have more and equal to 3 runes and your runic power is greater than 60

the second one is being called without bos, and the req are pof ready,  time to have 5 runes is greater than the gcd and rp déficit equar or greater than 10


I just logged ingame and it was suggesting it. Pof isnt suggesting probably because you have bos talented and first you need to use erw, then pof then bos

**Comment by DLSauron** [comment]
No I have Obliteration talented not bos. I  assume if I am following the rotation suggest by the addon it would lead me to point that erw would be suggested, but that does not appear to be happening.

**Comment by DLSauron** [comment]
Created a  short video. If you watch it only ever suggests erw at the very start and then it disappeared. It never suggests pof. I did not use erw or pof at any point of the video.

https://youtu.be/RkJAyhcmbkA

**Comment by Cilraaz** [comment]
The Frost DK profile was updated on Dec 21, 2018. The APL changes should have fixed this issue. If it has not, please create a new issue.
