### ISSUE TITLE
[Enhancement] Lava Lash

### ISSUE THREAD

**Issue by dhaos21** [herotc/hero-rotation#249]
In the latest alpha the rotation no longer calls for Lava Lash to be used.

**Comment by lithium720** [comment]
Lava lash is only called for if you're talented into Hot Hand. Are you talented into hot hand?

**Comment by lithium720** [comment]
Previously It may not have been a requirement for the rotation, but that is how the SimC APL it setup now. So it's reflected in the rotation. I have noticed myself maelstrom capped a lot too. Something to take up with whomever maintains the APL.

It's more than likely only a problems because our stats aren't high enough yet.

**Comment by dhaos21** [comment]
just had a look at the latest simc and they have 2 parts

Lava_lash,if=talent.hot_hand.enabled&buff.hot_hand.react

and under filler

lava_lash,if=variable.OCPool80&variable.furyCheck45

so looks like we still should be using lava lash when we hit 80 maelstrom to stop us sitting on cap until Stormstrike comes off CD.
