### ISSUE TITLE
Windwalker monk being given the same suggestion multiple times in a row

### ISSUE THREAD

**Issue by Barleduq** [herotc/hero-rotation#288]
This is bad for windwalker monk, which wants something different from the one before each time in order to maximize dps.  I've been seeing this for a while, even as other parts of the rotation have settled into making more sense. 90% of the time (it seems) I'm getting blackout kick repeated - up two 4 cycles before it decides on something else. (In the meantime, I'm not listening (lalalala))  Sometimes it's Rising Sun Kick, rarely it's Tiger Palm. Unfortunately, I don't know how to record my sessions, so I can't show you. :(  

Is HR taking into account azerite armor bonuses?  If so, I do have something that benefits Blackout Kick. I don't know if that benefit counteracts the general loss. 

-Barleduq

**Comment by Hinalover** [comment]
Are you working with the most recent Alpha version? If so what traits/talents are you running with? I personally have not seen this happen recently. There was a bug about a week or so ago where it was capping on energy due to checking on the duration of Fists of Fury was causing issues. that was recently fixed.

**Comment by Hinalover** [comment]
The only time in which the addon SHOULD cast 2 Blackout Kicks in a row is during Serenity. This is due to trying squeeze in as many RSKs within Serenity.

As for Swift Roundhouse, both the APL as well as the addon should not be checking for Swift Roundhouse traits; other than trying to hit 2 stacks of the SR buff before casting RSK.
