### ISSUE TITLE
[UI] Icons greyed out when out of range

### ISSUE THREAD

**Issue by aethys256** [herotc/hero-rotation#31]
Instead of no icon displayed

**Comment by Aethys256** [comment]
Need a bigger rework than thought, mostly due to the fact that what spell should be displayed when not in range, a replacement one that is castable or a greyed one ?
I guess we should always display whatever is castable and if nothing matches the conditions then display the first one that matches every conditions but the range.

**Comment by mspykerez** [comment]
Can icons be greyed out when not enough energy too ?
