### ISSUE TITLE
[UI] Predictive icon for second ability to use.

### ISSUE THREAD

**Issue by ashkashlitwin** [herotc/hero-rotation#37]
There's an icon for what to use right now, but it's typically a very short window (1 or 1.5 sec GCD) to see the ability used and the next ability suggested, visually process the icon change, and decide which button to press (and typically AethysRotation would have a very small delay AFTER pressing the button to calculate the ability change as well, shortening that already short window)
Other rotation helpers I've used all have at least 1-step-forward predictive icons to help guide the brain in processing the next ability, and I found it heavily disconcerting not having that aid in AethysRotation as a new user.

**Comment by Aethys256** [comment]
It's something that is recurring on the Discord, I'll take a look at it to make it reliable (which isn't easy for every specs). Although, it's not the high prio for me atm.

**Comment by Aethys256** [comment]
The team isn't sure yet if it's something we want to implement or not.
In any case, if we do so, that'll be for BfA and later on.

**Comment by tristangreeno** [comment]
Would that be a case for machine learning of some sort? It would need to have a neural network of some kind in order to predict the possible futures correctly.

**Comment by Barleduq** [comment]
I'm a new user of the addon, and I came here looking to see what was possibly being worked on. The rotation addon I have been using, Taraezor's We Don't Wipe, does this - has a line of up to 10 icons, predicting next to use. The ones at the tail end swap around a lot (and I've never seen all the slots used), but, at least for windwalker and frost mage, it's very effective. (I'm trying to move to Aethys because Taraezor has indicated that he's not really interested in keeping that addon going. And Aethys works with more classes.)

**Comment by aethys256** [comment]
Prediction is a field that we'll not adventure, at least not until a long time.
The addon is reactive, mostly due to procs, exactly like SimC is.
While some prediction logic can be added (and is already added for some ranged during a cast for example), predicting the upcoming sequence isn't something easy and reliable to do at the moment.
