### ISSUE TITLE
 Too much idle in ADK rotation

### ISSUE THREAD

**Issue by narvell3** [herotc/hero-rotation#394]
I want to ask the person who leads the branch of rotation on the ADK. Please tell me when you fix the rotation? I wrote a previous post about the trinket, and now it was noticed that there are so many downtime in the rotation that the horror is simple. The same Hekili shows that you need to reap the free Death Coil and you have written "POOL". I ask you please, dear developers, correct the rotation of the ADC. Why do you rule the FDK but ignore the ADK class?

**Comment by Cilraaz** [comment]
Unholy was updated to change some function names. Otherwise, it hasn't really been updated since September. If I have time this evening, I'll see about regenerating a profile against SimC's T23 APL.

**Comment by narvell3** [comment]
Thank you for not tidying up a lot of Unholy DK, there was less downtime, but it didn’t disappear completely. I see that I have 2 runes, but the program writes POOL, although another program shows that I can hit spells at this moment. You need to recycle the logic. If anything, I have a WA rotation, which I can drop to you and you can correct the rotation based on it. Let me know if you need a WA rotation on the ADK.

**Comment by Cilraaz** [comment]
If you're still getting the "Pool" icon, you have an older version of the profile. 

If you update via the Twitch client, you can set the Hero Rotation type to alpha to get the latest updates. To do this, right click Hero Rotation, go to Type, and select Alpha. 

Otherwise, please be sure to grab the latest version from the github. It should be much improved.

**Comment by Cilraaz** [comment]
4 days with no response. If this is still a problem with the latest version, please re-submit an issue.
