### ISSUE TITLE
Feral [Primal Wrath] 

### ISSUE THREAD

**Issue by p4nchez** [herotc/hero-rotation#428]
hi
if i have 5 combo points and 4+ targets around me why rota suggest me to make a rip instead auf a Primal Wrath?

in aoe groups it trys allways first to maintane rake and rip on a single target and then in the group it would spred primal wrath next time i hit 5 points

hekeli suggest on my first 5 combo points do primal wrath instead a single rip if there much mobs around me and thats is what i should go?

is there a way to get primal wrath prio over rip if there 3+ mobs ?
its waste of AOE dmg if i do a single rip in a trash mob group 

look at my screenshot
5 points and rake on one target
hero roation shows RIP icon
hekeli suggest primal wrath

so dont understand me wrong hero rotation shows me primal wrath BUT only after it suggest a full RIP on one mob and then with next time 5 combo points shows primal wrath
![feral](https://user-images.githubusercontent.com/29162840/57257812-d25a1f80-705a-11e9-92dc-659f66e3fab8.png)

**Comment by Cilraaz** [comment]
I'm guessing that this was in the initial opener. If you enable debug output, I'd guess it's suggesting "rip 388". After the initial Rip, it's probably working properly. I changed the opener to use Primal Wrath if there are 2+ targets instead of the initial Rip.

This should be fixed in commit https://github.com/herotc/hero-rotation/commit/bcb416f2dc538789a58aea37e6de05122afe8d9c

Please let me know if this resolves your issue.

**Comment by p4nchez** [comment]
resolved
thx <3
