### ISSUE TITLE
[Arms/Fury] Range issues and heroic leap out of main icon.

### ISSUE THREAD

**Issue by azzi1103** [herotc/hero-rotation#467]
Still having range check issues. Also having heroic as suggestion and not main icon on fury warrior.

**Comment by Cilraaz** [comment]
What range check issues? Also, Heroic Leap is only ever suggested as a main icon ability.

**Comment by azzi1103** [comment]
is there a reason why it has to be on the main icon? Also the range check issues is the same where the icons show up even though you're out of range from the target. happens on Arms and fury, and I assume same issue on Prot warrior.

**Comment by Cilraaz** [comment]
Heroic Leap is only suggested while out of melee range for Fury, and it wasn't even in the Arms APL. It would be odd for it to show OffGCD while having nothing showing in the main icon, which is why it was left as a main icon only. I added an OffGCD toggle, though (disabled by default).

Fury already had range checks in the profile. I added them for Arms. Check out commit https://github.com/herotc/hero-rotation/commit/167378fefd28418849b16073f9b7868615d220a4

I added:
- Fury: Added Heroic Leap OffGCD toggle
- Both: Added ChargesP() >= 1 check to Charge so it won't be suggested
if there are no charges
- Arms: Added Heroic Leap ability and its OffGCD toggle
- Arms: Added range checks to most spells (essences, buffs, and AoE such
as Bladestorm omitted for now)
- Settings: Removed OffGCD for old potions and items

Let me know if anything else needs tweaked.

**Comment by azzi1103** [comment]
thanks, i will be testing a bit more as well, currently playing arms, but I will swap to fury to see how it works now :)

**Comment by azzi1103** [comment]
Also if using 3x Test of might, don't you want to dump as much Rage as you can after warbreak use? Bladestorm keeps getting suggested after a warbreak in singletarget. Would rather be better to have it as a gap filler right?

**Comment by Cilraaz** [comment]
The SimC APL makes no reference to the number of ranks of Test of Might. There are only a few references to Test of Might at all and none are regarding dumping rage.

**Comment by azzi1103** [comment]
the apl is fine, just having Bladestorm in the main icon ruins the rotation itself. I put it on suggested instead and it seems to be doing way better. So idk if you could fix the bladestorm to not to be used during Warbreaker buff unless it's +4 targets in AOE. Because during the Warbreaker you wanna dump as much rage as you can to get higher strength buff from test of might.

**Comment by Cilraaz** [comment]
Bladestorm has multiple use conditions depending on target count. HR currently aligns with SimC.
