### ISSUE TITLE
Outlaw rogue, roll the bones getting suggested 15-20 sec earlier than it should be.

### ISSUE THREAD

**Issue by azzi1103** [herotc/hero-rotation#469]
If I roll anything useful, the rotation suggests to reroll when i still have 12-20 sec of the buff

**Comment by azzi1103** [comment]
This doesn't happen every time. Any explaination for this?

**Comment by Mystler** [comment]
I'd bet what you're seeing is rerolling Ruthless Precision because your cooldown on Between the Eyes is higher than the remaining time on the buff and should be working as intended. There are cases when CDR would give you one more use of it but simulations have not shown these to be noticeably better than just rerolling a bit earlier.

**Comment by azzi1103** [comment]
Okay thanks for explaining, I was unsure about this. Since im using 3x ace up your sleeve, and rerolling the Ruthless Precision was like a bit confusing.
