### ISSUE TITLE
[Enh Shaman] Issues introduced for enh with 8.0.2.00

### ISSUE THREAD

**Issue by JakubSloniec** [herotc/hero-rotation#478]
the following errors appeared in 8.0.2.00 release, worked stable in 8.0.1.12

1. When selected `Elemental Spirits` talent, the addon constantly throws the following exception:
```
[16:15:58] Interface\AddOns\HeroRotation_Shaman\Enhancement.lua:173: attempt to index global 'feral_spirit' (a nil value) 
[16:15:58] Interface\AddOns\HeroRotation_Shaman\Enhancement.lua:173: in function <Interface\AddOns\HeroRotation_Shaman\Enhancement.lua:171>
Interface\AddOns\HeroRotation_Shaman\Enhancement.lua:548: in function `?'
Interface\AddOns\HeroRotation\Main.lua:439: in function <Interface\AddOns\HeroRotation\Main.lua:417> 
[16:15:58] InCombatSkipped
```

2. When selected other 100-tier talent (Acendance in my case), the following exception sometimes is constantly thrown, reload fixes it for some time:

```
[16:23:27] Interface\AddOns\HeroRotation_Shaman\Enhancement.lua:507: attempt to index global 'essence' (a nil value) 
[16:23:27] Interface\AddOns\HeroRotation_Shaman\Enhancement.lua:507: in function `Priority'
Interface\AddOns\HeroRotation_Shaman\Enhancement.lua:558: in function `?'
Interface\AddOns\HeroRotation\Main.lua:439: in function <Interface\AddOns\HeroRotation\Main.lua:417> 
[16:23:27] InCombatSkipped
```

3. `Feral Spirit` and `Ascendance` are always shown in rotation (Ascendance only if the talent selected), both are never shown in `Off GCD` regardless the toggles value
- show as Off GCD: Feral Spirit [on/off]
- show as Off GCD: Ascendance [on/off]
- show Feral Spirit in rotation [on/off]

**Comment by Cilraaz** [comment]
Issue 1 is fixed in commit https://github.com/herotc/hero-rotation/commit/ffe93a1c8e742c2f1ba042847370050f8c9f10d6

Issue 2 is fixed in commit https://github.com/herotc/hero-rotation/commit/e3527bce8280207f06edacacb085a3e6c47c1dd6

Issue 3 is fixed in commit https://github.com/herotc/hero-rotation/commit/5ae85b84101698f24528aec3d175cc82aca1c94e

If updating via the Twitch app, please set the addon to Release Type alpha to receive the latest updates.

**Comment by JakubSloniec** [comment]
tested.
confirming issue 1 fix.
confirming issue 2 fix.
issue 3: both `Ascendace` and `Sundering` shows correctly in `Off GCD`, but not `Feral Spirit`.
Tested with both `Ascendance` and `Elemental Spirits` talents for 100-tier.
Tested in scenario where all other `Off GCD` skills were on CD so that `Feral Spirit` would show up.

Additional issue 4: noticed that with current release there are situations where
- I'm lacking `Maelstorm` resource

- the current skill icon (ex.  `Stomrstrike`) is grayed-out
-

**Comment by Cilraaz** [comment]
Issue 3: Please double check your setting for Feral Spirit OffGCD. I was unable to replicate your issue and had Feral Spirit showing properly OffGCD. Please keep in mind that if more than 2 abilities are showing OffGCD, only the first two suggestions will show.

Issue 4: I committed a change to make all maelstrom-using abilities use IsReadyP instead of IsCastableP. This should fix the issue of unusable spells being suggested.

**Comment by JakubSloniec** [comment]
Issue 4: now fixed with the latest commit, though it's now often the case that there is no suggested skill, though it's understandable
Issue 3: Please refer to the screenshot attached. Wind Shear, Ascendace and Sundering all on CD, and Feral Spirit not showing as `Off GCD`. By the way its it's often the case that no skill is shown for `Off GCD`, sometimes the `Off GCD` skills appears for one suggested skill and then when skill is used they dissapear, and the appear again after 1-more used suggested skills. I have not noticed any pattern in this, though no 'Off GCD' skill is ever suggested at the beginnig of the fight.

![image](https://user-images.githubusercontent.com/8956562/63229079-ad9a4a00-c1fc-11e9-96de-b601576de4ab.png)

**Comment by Cilraaz** [comment]
Issue 3: You have "Show Feral Spirit in rotation" unchecked. So it will never show.

**Comment by Nordaar** [comment]
that clarifies a lot, thanks. I have misunderstood how those toggles work.

regarding the showing and not showing of the `Off GCD` skills, those screenshots were taken after each used suggested skills, they are ordered consecutively:
![WoWScrnShot_081819_224219](https://user-images.githubusercontent.com/8956562/63230192-ad547b80-c209-11e9-9375-b448354d538c.jpg)
![WoWScrnShot_081819_224221](https://user-images.githubusercontent.com/8956562/63230194-b04f6c00-c209-11e9-84a0-14d4999917dd.jpg)
![WoWScrnShot_081819_224223](https://user-images.githubusercontent.com/8956562/63230195-b1809900-c209-11e9-939e-c2c0576315ee.jpg)
![WoWScrnShot_081819_224225](https://user-images.githubusercontent.com/8956562/63230202-c4936900-c209-11e9-8485-f104943b95ae.jpg)
![WoWScrnShot_081819_224227](https://user-images.githubusercontent.com/8956562/63230203-c6f5c300-c209-11e9-949a-ef5b4752be73.jpg)
![WoWScrnShot_081819_224229](https://user-images.githubusercontent.com/8956562/63230207-d543df00-c209-11e9-8b1b-67c8d9687ecf.jpg)
![WoWScrnShot_081819_224231](https://user-images.githubusercontent.com/8956562/63230209-d7a63900-c209-11e9-8af7-42f44930eae6.jpg)

**Comment by Cilraaz** [comment]
Can you provide the same screenshots, but with debug output enabled? There are multiple instances of Crash Lightning in the profile and it'd be easier to know which one is causing the potential issue.

**Comment by Nordaar** [comment]
there you go. tell me if you need anything else

![WoWScrnShot_081919_000425](https://user-images.githubusercontent.com/8956562/63230973-1ab9d980-c215-11e9-9cd3-75f04839bb58.jpg)
![WoWScrnShot_081919_000427](https://user-images.githubusercontent.com/8956562/63230975-1d1c3380-c215-11e9-91e5-e669c9f44fa5.jpg)
![WoWScrnShot_081919_000429](https://user-images.githubusercontent.com/8956562/63230978-20172400-c215-11e9-983a-f366b665c321.jpg)
![WoWScrnShot_081919_000430](https://user-images.githubusercontent.com/8956562/63230979-21e0e780-c215-11e9-8b18-9a46d75f3c56.jpg)
![WoWScrnShot_081919_000431](https://user-images.githubusercontent.com/8956562/63230982-29a08c00-c215-11e9-922c-82ed423cf6f2.jpg)
![WoWScrnShot_081919_000433](https://user-images.githubusercontent.com/8956562/63230983-2c02e600-c215-11e9-9766-816556c82b0a.jpg)
![WoWScrnShot_081919_000434](https://user-images.githubusercontent.com/8956562/63230984-2dcca980-c215-11e9-9153-8e94fb506a3d.jpg)
![WoWScrnShot_081919_000436](https://user-images.githubusercontent.com/8956562/63230985-302f0380-c215-11e9-998d-78d2baec498a.jpg)
![WoWScrnShot_081919_000438](https://user-images.githubusercontent.com/8956562/63230986-32915d80-c215-11e9-9005-756d3231f467.jpg)
![WoWScrnShot_081919_000439](https://user-images.githubusercontent.com/8956562/63230987-34f3b780-c215-11e9-9d85-93b7c1881f98.jpg)

**Comment by Cilraaz** [comment]
The spells that are stopping OffGCD spells from showing are from action lists called before the CDs list that contains those OffGCD spells. Since they're finding a main icon spell to suggest, the profile never gets to the CDs list to find things like Feral Spirit.

If I've read the core code properly, a main icon Cast function call returns true, ending that iteration of the profile and starting a new one. Meanwhile, an OffGCD Cast or a CastSuggested returns false, allowing the profile to keep going in the search for a spell to suggest as the main icon. 

All that to say that the behavior you're seeing is the correct behavior of the addon and Enhancement profile. There may be a good way to change this while keeping to the intent of the APL, but I'm not familiar enough with Enhancement to decide what change(s) would work.

**Comment by Nordaar** [comment]
should I create an enhancement request for this?

**Comment by Cilraaz** [comment]
It's not so much an enhancement being required as it's just the order of the enhancement APL.
