### ISSUE TITLE
fire mage

### ISSUE THREAD

**Issue by elmurjfudd** [herotc/hero-rotation#502]
no matter which talents i have selected add on always has scorch as a filler never fireball and it doesnt seem to reccomend fireblast unless rune of power is down and then only once at the start and rune and then not again til next rune of power running latest alpha HeroRotation-8.0.2.00-64-g97b97f4-alpha.zip

**Comment by elmurjfudd** [comment]
sorry edit if i disable 
![image](https://user-images.githubusercontent.com/55065713/64495068-1193b980-d263-11e9-9a4b-84c97bb8bb43.png) ist fixes single target rotation

**Comment by Cilraaz** [comment]
I'm unable to reproduce this issue. Please provide your talent setup, essence in use, and azerite traits.

**Comment by elmurjfudd** [comment]
figured it out talents and traits dont matter it only happens when combustion is off cd and u dont use it like for trash mobs before a boss feel free to try to reproduce again on a dummy but dont use combustion it will suggest scorch

**Comment by Cilraaz** [comment]
This is the same as issue #491. Unfortunately, due to the way the SimC APL is laid out, the profile can't anticipate or adapt to delaying use of Combustion. There may be changes down the line to handle this, but, at this time, it's not possible to adapt to the delay of Combustion and keep with the intent of the SimC APL.

**Comment by elmurjfudd** [comment]
Damn ok then I'll close it out
