### ISSUE TITLE
[FDK] Is it possible to disable the preparation for BoS? Via a button or checkbox.

### ISSUE THREAD

**Issue by narvell3** [herotc/hero-rotation#506]
Hello. I already asked you, by the way, how to turn off preparation for BoS. You were then advised to click Cds Off and the addon will not follow BoS. But as a result of the raid run, I realized that if there is always Cds Off, then the rotation will not work correctly. And if with Cds On enabled then BoS will not be used where I need it. I understand maybe this topic has already been touched upon earlier, but the point is that I would like to be able to somehow disable the BoS preparation in the add-on without disrupting rotation, and then when we need to use BoS just by clicking Checkbox or the button, rotation will again follow BoS . Is this possible to implement? or not. Thanks in advance for your reply.

**Comment by Cilraaz** [comment]
Disabling CDs bypasses both the BoS Pooling function and the Cooldowns function, which I believe is why the rotation does not feel right without CDs being enabled, as the Cooldowns function includes usage of Pillar, ERW, Frostwyrm's Fury, etc.

I could add a new settings option to disable the BoS Pooling function, so that toggling that option only bypasses the BoS Pooling function. BoS would still be suggested inside the Cooldowns function, but could be forced to the OffGCD position in this scenario.

I can't promise that this would be optimal, as the SimC APL and HR Profile don't assume that you will hold an ability once it's been suggested, but it should function more in the manner that you are asking. It would not be a simple toggle, but rather a normal settings checkbox.

Let me know if this is something akin to the change you're requesting.

**Comment by narvell3** [comment]
Yes, I think it would be great to be able to see visually when it is possible to use BoS and when not. I could recommend doing to the left of the rotation how you did it with Dot Tracking. In this place, you could put figuratively the inscription "BoS Ready". It's just that in OffGcd I have so many trinkets and essences there.
P.S. I would also like to notice another problem: there is no way to selectively select trinkets and their position in the addon. Suppose I would like the coral to be in the Main icon and the trinket from Azshara, I would like it to be displayed in offgcd. This is implemented by the way in hekilli where you can change the trinkets and their display yourself.

**Comment by Cilraaz** [comment]
I can add a dropdown toggle for BoS positioning, similar to Trinkets and Essences.

Trinkets and Essences have the option to be in the OffGCD (above the Main icon) or Suggested (left of the Main icon) positions. It would not currently be possible to change them on an individual item basis.

**Comment by narvell3** [comment]
I think it’s better on the left to make more space there, and a better concept will be when it is ready.


Thank you for your help. I understand that it seems wild to you why I want to manually control BoS, but there are times in the raid where I should not give BoS from time to time, namely, wait for this moment to use BoS afterwards. I don’t get this mechanics because of such trifles. For this, I apologize for such a request.

**Comment by Cilraaz** [comment]
Updated in commit https://github.com/herotc/hero-rotation/commit/80200236a1ec4e605a052de2dbb8ac616c77d026

There's now an option to disable the BoS Pooling function and a dropdown selection for the location of the BoS icon.

Let me know if it doesn't work as expected.
