### ISSUE TITLE
Assa Rogue Pooling Question

### ISSUE THREAD

**Issue by Buddhaman1** [herotc/hero-rotation#517]
How is the pooling for assa rogue structured? Is there a base level it's playing around or looking for certain queues to pool or not pool - just curious

**Comment by Mystler** [comment]
The rotation is based on the SimulationCraft APL. For the technical details, you can check that one out here: https://github.com/Ravenholdt-TC/Rogue/wiki/Assassination-APL-Research

In simpler form, sometimes it will show pooling when you do not meet the energy for an ability, but mostly it should be before Envenom outside cooldown windows. The current APL was found to work best with that kind of pooling because it ensures you have a good amount of energy ready while also makes some good uptime on EP and the Envenom buff. The pooling amount is based on energy and energy regeneration.
