### ISSUE TITLE
Rotation Settings Adding CD's

### ISSUE THREAD

**Issue by arkencl** [herotc/hero-rotation#524]
Sometimes I feel like I'd like to put Apocalypse (Unholy DK) or Storm/Earth/Fire (WW Monk) on the side where other cooldowns are put. Is that thing that would make sense for the addon to allow? 

I find myself personally wanting to continue the rotation, because I am able to see that the pack will die before I get the full value out of the cooldown, but the addon recommends it either way (that I should use Apocalypse regardless because Festering Wounds are at a certain amount of stacks and whatever other factors play into it) because it lacks the ability to differentiate that context.

**Comment by Cilraaz** [comment]
In the Unholy DK profile, there are a large number of conditions for both AoE and ST functions that check if Apocalypse has a cooldown remaining. Pushing Apocalypse to OffGCD and not using it would pretty well mangle the rest of the profile, which is why it's still forced into the main icon.

WW Monk has much fewer conditions that check against SEF. When I checked WW, the profile is already forcing SEF to be OffGCD. I've changed that to be a toggle option instead, though.
