### ISSUE TITLE
Vengeance DH Error version 8.2.5.01-24-g2dd7009-alpha

### ISSUE THREAD

**Issue by nucce1** [herotc/hero-rotation#525]
#### Issue description
Latest version spamming error messages when playing as Vengeance Demonhunter.

#### Steps to reproduce the issue
Engage combat as Vengeance DH

#### What's the expected result?
No error messages.

#### What's the actual result?
Bugsacker is spamming the following:
```
3089x HeroLib\Events\InFlight.lua:78: You forgot to register Concentrated Flame for InFlight tracking.
[C]: in function `error'
HeroLib\Events\InFlight.lua:78: in function `InFlight'
HeroRotation_DemonHunter\Vengeance.lua:252: in function `Cooldowns'
HeroRotation_DemonHunter\Vengeance.lua:357: in function `?'
HeroRotation\Main.lua:439: in function <HeroRotation\Main.lua:417>

Locals:
(*temporary) = "You forgot to register Concentrated Flame for InFlight tracking."
```

#### Affected Version
8.2.5.01-24-g2dd7009-alpha

#### Working version
No errors when I play with the previous version 8.2.5.01-23-g0338065-alpha

Full Regards

**Comment by Cilraaz** [comment]
There were no changes to VDH between the two mentioned commits. The error will only occur when your main essence is changed to grant the Concentrated Flame ability. This _should_ have been fixed in commit https://github.com/herotc/hero-rotation/commit/a8e565a6c15a9c213fd651e9653012c45459b94a on Dec 2, 2019.

I'll do some testing to see if I can replicate the error.

**Comment by Cilraaz** [comment]
This issue has been fixed for VDH as of commit https://github.com/herotc/hero-rotation/commit/d0eebb4a82ec2a327903252698922e7ae809498f
