### ISSUE TITLE
Windwalker AoE rotation not activating

### ISSUE THREAD

**Issue by uino59** [herotc/hero-rotation#557]
Following commits d4f594a and c3ff484, HeroRotation becomes active on boss fights but is not displaying anything on trash packs in dungons or on dummies. Reloading the game, and reinstalling HeroRotation had no effect, however I have only been able to test this on one PC.

On boss fights, it is also suggesting Touch of Karma immediately following a Touch of Death as part of the main rotation which, to me, seems sub-optimal as in raids and boss fights it is often wiser to hold ToK for damage phases, rather than in the first 15 seconds of the fight where the monk may not actually be receiving damage to feed ToK. To me, this would be better as a side suggestion rather than preventing any further rotation suggestions until ToK is activated.

**Comment by Cilraaz** [comment]
The error in the updated version should be fixed in commit https://github.com/herotc/hero-rotation/commit/d6645f3b80190c159a74a2b58e8b4b224cd3b47c

I had not added the ranges used by the new FightRemains filters to the function that generates the cache of enemies at certain ranges. So, they were always returning nil. 

I also added a toggle option to ignore Touch of Karma. Enabling this will allow you to use ToK when you'd prefer, rather than when the addon suggests.

**Comment by uino59** [comment]
Lovely stuff. Thanks for all the work you guys do on this addon, it really is a lifesaver (often literally!).
