### ISSUE TITLE
Target:GetEnemiesInSplashRangeCount(range) returns not more than 1

### ISSUE THREAD

**Issue by Nmxsz** [herotc/hero-rotation#589]
in my opinion it should return the count of all enemies in splash range i dont know if its bugged know or if it works as intended

**Comment by Cilraaz** [comment]
It returns the number of enemies within the splash range, calculated based on enemies hit by AoE spells. It will calculate based on your AoE spells, as well as group/raid member AoE spells. It has been tested and appears to be working as intended, unless you've found a specific scenario where it doesn't.

**Comment by Nmxsz** [comment]
okay i tested it on enhancement shaman and it only works for chain lightning
https://imgur.com/a/Y0E1Zfm

**Comment by aethys256** [comment]
This is because it's meant to be used by ranged, melees like enhancement should use the API that use ItemRange not CombatLog.
Also we do not support every cast type nor spells.

Spells: https://github.com/herotc/hero-lib/blob/shadowlands/HeroLib/Events/SplashEnemies.lua#L373
Type: https://github.com/herotc/hero-lib/blob/shadowlands/HeroLib/Events/SplashEnemies.lua#L344

If you really need splash range but do not have a supported spell, it will still work when you're playing in a party/raid since it tracks them.
