### ISSUE TITLE
Covenant Abilities are not appearing on main Icon

### ISSUE THREAD

**Issue by winnerwinnington** [herotc/hero-rotation#661]
In Hunter Hero Rotation config - if I set covenant to appear on main icon, it stops showing up on cool down, but does not appear on the main icon ever.

**Comment by winnerwinnington** [comment]
This is happening in BM spec, and I suspect MM too.

**Comment by Cilraaz** [comment]
I found that the covenant abilities in BM (and a couple in Survival) were not properly returned, causing the profile to suggest the covenant ability, but then immediately go on to the next suggestion. I did not find this issue in the MM profile.

This should be fixed in commit https://github.com/herotc/hero-rotation/commit/86568292b40ccb507b3bdd557f8c7c2285a52e71
