### ISSUE TITLE
Warrior - Venthyr Condemn

### ISSUE THREAD

**Issue by dmillerlx** [herotc/hero-rotation#710]
I can't seem to get Venthyr Condemn to show in the rotation.
I confirmed the spellId is 330334, but it seems to never show condemn as the next action.
I added some debug statements and I think arms.lua ~ 216 is not working as expected.

`
if HR.Cast(S.Condemn, nil, Settings.Commons.CovenantDisplayStyle, not Target:IsSpellInRange(S.Condemn)) then
`

![Condemn debug](https://user-images.githubusercontent.com/10935489/105804660-34586800-5f55-11eb-8c73-84da1757bcfe.png)

![Condemn Not Working](https://user-images.githubusercontent.com/10935489/105804579-007d4280-5f55-11eb-8ae4-3500fb1b7bb5.jpg)

Let me know if you need any additional details.

**Comment by ryanbowen** [comment]
It's behind your Overpower icon.

**Comment by dmillerlx** [comment]
Thanks for the quick response.  I was not expecting to see another icon to the upper left of the main action showing Condemn.  Was expecting to see the main action replaced by the Condemn icon.

I cleaned up the UI and repositioned it, and can clearly see the slam and condemn icon.

![WoWScrnShot_012621_024011](https://user-images.githubusercontent.com/10935489/105835928-5c5dc080-5f81-11eb-9c8b-823dfc8ba694.jpg)

**Comment by Cilraaz** [comment]
You can use the Covenant Display Style option to change the location of your covenant abilities between "Suggested" (upper left, where it currently is), "Main Icon" (the... main icon), and "Cooldown" (above the main icon with other 'OffGCD' abilities). Trinkets have this same option. It's found under the class options, rather than spec options.
