### ISSUE TITLE
[DK-UH] The long-distance epidemic does not work and there is no support for trinkets.

### ISSUE THREAD

**Issue by geraint425** [herotc/hero-rotation#715]
Hello. Thanks for the updated rotation. And I am testing a new assembly, I noticed that the epidemic does not work correctly at long distances. It turns out when I use Outbreak on a target and run away from them, I am not offered an epidemic in rotation, it occasionally jumps, but not always. I also noticed that there is no trinket support. I tried both from the raid and from Mythyc+ the addon does not offer them in rotation.

**Comment by Dragonfo** [comment]
Also noticing having gone to the raid. That during the ST fight with the boss, an epidemic, Death and decay may be offered to the rotation. And I tried to enable and disable on the ST and AOE panels, these abilities were still offered in the rotation. I also noticed that the addon offers little to press on the execution phase
He begins to offer Soul Reaper conditionally somewhere at 45-50%, and after that he can already ignore this ability, and rarely offer it. But it should be used by CD.

**Comment by Cilraaz** [comment]
@narvell3 I added an out of range check for epidemic. It will be suggested if it's able to be casted, at least 1 target has Virulent Plague, we shouldn't be pooling RP (per the APL variable), and we have zero targets within 8 yards. Trinkets are 100% supported. Make sure that you have "Show Trinkets" enabled in your class settings.

@Dragonfo Epidemic is not suggested when there is only one target within 8 yards. It only exists within the AoE functions, which require a target count of 2+. (Well, it's now included in the main function in the case of zero targets within 8 yards)

Soul Reaper should be suggest on cooldown. The exact requirement is target will be under 35% hp in less than 5 seconds and will live for more than 5 seconds. In multi-target situations, it will potentially be suggested for targets other than your main target. I've changed this to prefer the primary target if the conditions are met, however.

Death and Decay _should_ be offered in the single target rotation under the following conditions: 
- Apocalypse is on cooldown
- One of: Defile talent is selected, Covenant is Night Fae, or Phearomones legendary is equipped
- One of: We are not pooling runes (per the APL variable) or the fight will end in less than 5 seconds

These changes have been included in commit https://github.com/herotc/hero-rotation/commit/586d193208173310d209eaea0d82bed5dca060ee

**Comment by Dragonfo** [comment]
Thanks for the fix. But there are some problems. It turns out that the addon does not seem to react to the AOE button. I seem to be pere-toggling and the rotation does not change, with AOE when I am with 4+ targets. Plus, an interesting thing was noticed. That if I run very far away from the CT target, then an epidemic is suggested. And this should not be. Since the epidemic is only effective when there are 2+ targets. In fact, I can only use death coil at a distance. Then it was also noticed that death and decay does not want to appear in the main icon. I seem to be doing the rotation correctly, but as soon as the turn comes to death and decay there is simply a POOL icon. And if I myself press death and decay, then everything works fine, and the POOL will always hang on the machine when there is a battle with 4+ targets. And so with the epidemic and the Soul reaper everything is fine. Just fix the above points and, in principle, there are no problems. Thanks again for your help.

**Comment by Dragonfo** [comment]
and it was also noticed that the apocalypse is offered to be pressed, without stacks of Festering Wound. Or on 2 stacks

**Comment by Cilraaz** [comment]
Adherence to the AoEON setting has been added in commit https://github.com/herotc/hero-rotation/commit/449e4c21d993bc00847d6cf0cb4d5e10fd811e7f

I also changed the out of range Epidemic cast suggestion to require 2 targets with Virulent Plague, as well as adding an out of range Death Coil suggestion if less than 2 targets have Virulent Plague. Both of these suggestions are reliant upon the pooling_runic_power variable, however, and will not be suggested if we should be pooling RP for Gargoyle.

Apocalypse is only suggested when the current target is at 4+ stacks of Festering Wound.

Death and Decay is only suggested in specific scenarios. For AoE situations, all targets must have Festering Wound (or at least 5 targets, if there are more than 5 enemies). For single target, the conditions were laid out in my previous reply.

**Comment by Dragonfo** [comment]
This is all clear above, thanks for the fix, the bug with the apocalypse really exists. Because, you can check for yourself what the addon can offer it in rotation, but there is no Festering Wound on the target. I'm currently in a raid, and lust is given from the pool, and the rotation is perfect at the beginning, and as soon as it comes to the apocalypse, he offers to press it when there is no Festering Wound.

**Comment by Cilraaz** [comment]
Here is the line of code for the Apocalypse suggestion:

if S.Apocalypse:IsCastable() and S.Apocalypse:IsUsable() and ((EnemiesMeleeCount == 1 or not AoEON()) and Target:DebuffStack(S.FesteringWoundDebuff) >= 4) then

As you can see, it clearly requires a 4+ stack of Festering Wound. I've also not seen it ever suggested _without_ 4+ stacks of Festering Wound.

**Comment by Dragonfo** [comment]
https://imgur.com/a/G8UUgSl 
This is the rotation of the opener that the addon offers. here's my panel and take a look and you won't see my festering wound stacks on WA. 
https://imgur.com/a/JoNdre9 
And so I attached my talents that were taken from the covenant.

**Comment by Dragonfo** [comment]
So I turned on the debug, and took a screenshot where the error occurs. Where is it suggested to use the apocalypse without festering wound. https://imgur.com/a/4nncdZo

**Comment by Cilraaz** [comment]
It looks like this was a larger overall issue. This should be fixed in commit https://github.com/herotc/hero-rotation/commit/d4f47065c8cc8461f0afbd0a77e4efa726f22e2b
