### ISSUE TITLE
[Frost DK] Breath of sindragosa

### ISSUE THREAD

**Issue by Ankhy** [herotc/hero-rotation#721]
Using talents 3/1/-/1/-/1/3 it manages to make breath of sindragosa last for 1 - 3 tics. It just says pool after breat of sindragosa is up.

**Comment by geraint425** [comment]
I will support a higher person. It was also noticed that the addon, with a low value of runic power, prefers to press Howling Blast or
Remorseless Winter. Because there are 1-2 seconds left before Obliterate rollback. It seems to me that you need to raise Obliterate priority when using BoS. Because there were such moments that the same 1-2 seconds rolled back straight at a low value of runic power, and we could extend BoS by another 1-2 seconds. But the addon decides that it is not profitable, and simply ignores this moment.

**Comment by Ankhy** [comment]
Everyone.CastTargetIf(S.Obliterate, EnemiesMelee, "max", EvaluateTargetIfRazoriceStacks, EvaluateTargetIfObliterateBoSTicking2) is absolute rubbish. I changed it to HR.Cast(S.Obliterate, nil, nil, not TargetIsInRange[8]) and now breath of sindragosa lasts for almost 10 sec on first attempt

**Comment by geraint425** [comment]
You can please upload an already changed file, or indicate where you can change it. Thank.

**Comment by Cilraaz** [comment]
Frost DK has been updated to be in line with the 9.1 APL. This should be better now.
