### ISSUE TITLE
[Enhancement Shaman] rotation issue 

### ISSUE THREAD

**Issue by heilporsche** [herotc/hero-rotation#741]
If you are in a Party with other Enhancement Shaman windfury totem keeps showing up as suggested cast non stop, is it possible to to add windfurry totem as OFF GCD ? or fix the issue ?

**Comment by Cilraaz** [comment]
Unfortunately, Blizzard kind of ties our hands on totems. We have no way to track the time remaining on totem buffs, so we can only check either the time remaining on the totem or time since the totem was last cast. Neither of these work with other players' totems. As such, Windfury always gets suggested if it was last cast more than 90 seconds ago. I've added the requested OffGCD option for Windfury Totem in commit https://github.com/herotc/hero-rotation/commit/1e2a5b5fabbe887cfaaa5cb051b7979670de43b0
