### ISSUE TITLE
Holy and Shadow Priest no correct rotation.

### ISSUE THREAD

**Issue by ReglohPri** [herotc/hero-rotation#824]
There is no rotation more for shadow priest.

**Comment by Cilraaz** [comment]
It sounds like you're running an old version of the addon. 9.2.0.04 had a typo in the Priest profile. It was fixed in 9.2.0.05. This version doesn't appear to be showing on CurseForge for some reason, but is available [here](https://github.com/herotc/hero-rotation/releases/download/9.2.0.05/HeroRotation-9.2.0.05.zip)

**Comment by ReglohPri** [comment]
Thanks a lot.
Sometimes is the new version not forwarded to CurseForge.

Reglohpri -> Holger

**Comment by Cilraaz** [comment]
Sometimes their system does not pick up a new version for a few days. Sometimes it will randomly miss picking up an entire version. We haven't really been able to figure out why.
