### ISSUE TITLE
MM Hunter: on a 5 target training dummy setup I am being recommended arcane shot to consume precise shot procs

### ISSUE THREAD

**Issue by GarrettCottrell** [herotc/hero-rotation#837]
As the title states, on aoe I am being recommended arcane shots to consume precise shots. The correct recommendation to consume precise shot procs on aoe is Multi-Shot.

On 3+ targets, I should never be recommended an arcane shot. It seems to happen whenever I have a precise shot proc to consume, but of course that may not be the actual reason and instead just a coincidence - but the isssue is the same... there is no reason that on 3 or more targets I should be recommended an arcane shot for any reason

There is an odd behavior with this specific recommendation, which is that if I get the recommendation and then don't press anything for 1-2 seconds, it will eventually swap over to a multi-shot recommendation. So this arcane shot recommendation on aoe tends to flash and then sometimes quickly but sometimes very slowly swap to the correct multi-shot recommendation

HeroRotation Version 9.2.0.07
HeroDBC Version 9.2.0.01
HeroLib Version 9.2.0.01

Talents: 1/3/3/2/2/3/3

**Comment by GarrettCottrell** [comment]
Also with this same setup, on an aoe opener, after my 2nd aimed shot, it will always offer a steady shot recommendation (that swaps to a correct rapid fire recommendation but *only* afer the 2nd aimed shots full hits (so slowly enough that if I would have to pause for a global after my 2nd aimed shot in order to see the correct reommendation.

**Comment by Cilraaz** [comment]
Arcane Shot is not suggested in AoE. If it's being suggested, then the profile is not recognizing an AoE environment. What target dummies are you using? The addon may be excluding them.

**Comment by GarrettCottrell** [comment]
It is the stack of 5 in the kyrian covenant halls. Most of the time it is recommending multi-shot but arcane shot is recommended every now and then (same thing has happened in dungeons I've been in)

Another issue I'm noticing (that existed previous but I think the intension was to fix it with the 9.2 updates) is that on 2 targets, I am being recommended Multi-Shot. Not exclusively but it happens every now and then. This isn't exclusively the scenario but I think it may be picking up things like the tentacles on last boss of plaguefall and thinking they are enemy npc's and as a result recommending multishot when its just the boss up (this is just an example)

If it would be helpful, I can get VODs of all of this happening so at least you can see it in real-time and that may be helpful for diagnosing what's happening.

**Comment by Cilraaz** [comment]
> Most of the time it is recommending multi-shot but arcane shot is recommended every now and then (same thing has happened in dungeons I've been in)

This means that enough time has passed since an AoE action has occurred that the addon has reverted to single target. It should happen less often in groups, as group member AoE counts toward your target count. Data is kept for 5 seconds when solo, 4 when in a party (and in a dungeon), 3 when in a raid (and in a raid zone). So, in a situation where you're solo or working on target dummies, if you don't use an AoE for 5 seconds, the targets will be removed from the target table and the profile will revert to suggesting single target abilities.

> Another issue I'm noticing (that existed previous but I think the intension was to fix it with the 9.2 updates) is that on 2 targets, I am being recommended Multi-Shot.

Looking at the profile, I see no way for this to be happening. The single target function is called when less than 3 targets exist, and it does not include Multi-Shot. The Trickshots function is called on greater than 2 targets and includes Multi-Shot. So for the addon to suggest Multi-Shot, it has to be recognizing 3+ targets. This target count is taken from splash damage that hits targets within 10 yards of your current target. So to be included in the target count, the target must be hit by an ability, which _should_ discount things like the Plaguefall tentacles.

**Comment by GarrettCottrell** [comment]
That is very odd - the only thing that makes sense is that when it's recommending multi-shot, there must be something that my abilities are splashing onto (maybe?)

Not sure how else I can help other than to post a vod of some sort for evidence, so until I get that - there's not much more I can do to help because it does seem like there's no way for this to be happening.

**Comment by Cilraaz** [comment]
If the incorrect enemy count continues to be an issue, please let us know. Closing this issue for now.
