### ISSUE TITLE
[UI] Improvement: Keybinding Font Size

### ISSUE THREAD

**Issue by mrminus** [herotc/hero-rotation#87]
Hi. Thank you very much for adding the keybinding. I've been editing the UI.LUA to increase the font size of the keybinding each time you update. Would you please consider adding a UI element to change font size from within the addon. 

thanks.

**Comment by eleni195** [comment]
mrminus since you have this problem, you can probably answer to me this question. i want to make the ui so that it doesn't show icons. i want to see only the keybinds, and black icon in background.

i don't know if you can understand me, i just only want to see black, icons, and only the keybind sortcuts in white. can you please tell me how do i do it?

**Comment by Aethys256** [comment]
Hi, won't be an issue adding a slider for that. Thanks for the idea/report.

**Comment by eleni195** [comment]
Please tell me what I can do to only see key bindings

Στις 22 Δεκ 2017 18:40, ο χρήστης "Quentin Giraud" <notifications@github.com>
έγραψε:
