### ISSUE TITLE
Display Style Defensives set to Main Icon still shows as Suggested

### ISSUE THREAD

**Issue by lab1702** [herotc/hero-rotation#912]
Display Style Defensives set to Main Icon still shows as Suggested for Vengeance.
Version tested 10.0.2.28

**Comment by Cilraaz** [comment]
Fixed in commit https://github.com/herotc/hero-rotation/commit/b78d380b68d34455fb45f64676c033d3d34eeab8

- Demon Spikes and Fiery Brand (defensive use only) obeys Defensives DisplayStyle
- Metamorphosis (offensive and defensive use) obeys Metamorphosis DisplayStyle
- Fiery Brand (offensive use) obeys OffGCD setting
