### ISSUE TITLE
[Bug]: Outlaw Generic

### ISSUE THREAD

**Issue by GabbzGit** [herotc/hero-rotation#916]
### What version of HeroRotation are you using?

10.0.5.04

### What version of HeroLib are you using?

10.0.5.04

### What version of HeroDBC are you using?

10.0.5.04

### What is the issue?

Testing the rotation and looking at the code there are some things that is down prioritisating Ambush. Following the out of the box rotation i cast alot less Ambush and more SS then sims and is way down on DPS. When i changed somethings i got better result.

So my questions is:

- Ambush is not considering all buffs that allow it to be cast? My understanding is that there are the following which allows us to cast Ambust,  AudacityBuff, StealthUp, SubterfugeBuff, SepsisBuff. But alot of the Ambush cast is not considering all of them. 
- Also there is inconsistency for Ambush what to consider in the code. Line 537  versus 509.
- Line 504-507 does not check if there is stealth or buffs to allow Ambush to be used.

- There is inconsistency in regards to  S.Ambush:IsReady() and S.Ambush:IsCastable(). The difference is that IsReady(), i think is also checking if we have the resources? to cast it. However with CastPooling we want to pool but if the code is setting it to false we skip the pooling. Im not sure on this but why are we using different checks?

- There is inconsistency between Cast and CastPooling for a number of spells. Why should we not always pool for Ambush?

Appreciate the hard work and im not a coder so i could have missunderstood. 
Br

### Icon Behavior

No

**Comment by EvanMichaels** [comment]
Used this in raid all last night and had no problems. The issues you are pointing with the code are intentional. 

If you look at the APL the top instance of Ambush does not pool_resource,for_next=1. That is why one uses CastPooling with Ready vs Castable differences. 

We don’t need to explicitly check the buffs that enable Ambush. We just check the ability’s state in the client. API already tells us if the ability is usable or not. 

If you have a video or specific examples of it suggesting SS when Ambush was available for a HO build, can investigate. (Keep in mind that KiR builds are supposed to cast Ambush less frequently.)
