### ISSUE TITLE
[Bug]: Druid / Feral  - The keybind doesn t appear on feral form

### ISSUE THREAD

**Issue by Wagaaaaa** [herotc/hero-rotation#930]
### What version of HeroRotation are you using?

10.0.5.10

### What version of HeroLib are you using?

10.0.5.02

### What version of HeroDBC are you using?

10.0.5.02

### What is the issue?

The keybindings on feral form doesn t appear for the main bar, it does work for bar 2 and so.
![Capture](https://user-images.githubusercontent.com/126893978/222793545-a58bf9de-fb78-436e-97e6-8719b509186b.PNG)

### Icon Behavior

None

**Comment by Cilraaz** [comment]
Do you have Thrash on any other bar? Is it unbound on that bar?

**Comment by Wagaaaaa** [comment]
no, it s just on this one and it s the same for all the spell on the bar

**Comment by Cilraaz** [comment]
I've been unable to replicate this. It's likely due to the bar shifting associated with Druids and Rogues.

The way our hotkey detection works is that we have a big table of all of your possible buttons (all 120). Then, we iterate through them looking for the icon ID of the spell we're suggesting. The first button with a matching icon is identified as the match and its hotkey is plastered onto the main icon frame. 

So, usually this type of thing occurs when the spell (or another spell with the same icon) is on another button on another bar. We added some code to try to deal with the bar shifting issue a while back. Are you using a hotbar addon, by any chance? Maybe you're using one for which we don't have specific handling.
