### ISSUE TITLE
[Bug]: Enhancement ST Rotation seems a bit off after last update

### ISSUE THREAD

**Issue by RomansIX** [herotc/hero-rotation#940]
### What version of HeroRotation are you using?

10.1.0.03

### What version of HeroLib are you using?

10.1.0.01

### What version of HeroDBC are you using?

10.0.7.02

### What is the issue?

After i updated all my addons yesterday. It seems like every time, i go in to ST fights my icon's stop showing.
Fx. It tells "Windfury" "Flame shock" **Then nothing shows**

In aoe i dosent seem to have any problems.

This is my talent build: (Worked yesterday)
BcQAu3fz4tp2ZikXIAdNeR+oLIJJpEJISSISCUSkAAAAAAAAAAAAAKRICJkikCSLJpAOgSkEAC

### Icon Behavior

Icon disappears

**Comment by Cilraaz** [comment]
I'm unable to replicate this issue. Unfortunately, I only have a level 60 shaman, so it's possible I don't have the "right" combination of talents or items to cause the issue to occur.

Please enable lua errors. When the icon disappears entirely, it's due to a lua error 99% of the time. You can enable errors by either issuing the console command `/console scriptErrors 1` (you can later disable them with `/console scriptErrors 0`) or by installing the addon BugSack (which requires the addon BugGrabber).

If you do this and receive a lua error, please provide it here and I'll fix the issue ASAP.

**Comment by RomansIX** [comment]
Message: Interface/AddOns/HeroRotation_Shaman/Enhancement.lua:190: attempt to index field 'StaticAccumulation' (a nil value)
Time: Sat May  6 18:46:43 2023
Count: 32
Stack: Interface/AddOns/HeroRotation_Shaman/Enhancement.lua:190: attempt to index field 'StaticAccumulation' (a nil value)
[string "=[C]"]: ?
[string "@Interface/AddOns/HeroRotation_Shaman/Enhancement.lua"]:190: in function <Interface/AddOns/HeroRotation_Shaman/Enhancement.lua:132>
[string "@Interface/AddOns/HeroRotation_Shaman/Enhancement.lua"]:528: in function `?'
[string "@Interface/AddOns/HeroRotation/Main.lua"]:455: in function <Interface/AddOns/HeroRotation/Main.lua:433>

Locals: (*temporary) = <function> defined =[C]:-1

**Comment by Cilraaz** [comment]
This has been fixed as of commit https://github.com/herotc/hero-rotation/commit/04389a996f61c404448aa4200446460515cfd258

You can apply this commit by replacing the affected file (HeroRotation_Shaman\Shaman.lua) or it will be included in the next release version.

**Comment by RomansIX** [comment]
i'm kinda new at this, how do i do that :D?

**Comment by Cilraaz** [comment]
I just pushed version 10.1.0.04. It will show up in the usual places shortly and will contain the fix.

**Comment by RomansIX** [comment]
thanks for the great support!
