### ISSUE TITLE
[Bug]: Assasin Rogue Sepsis - Addon Recommends ambush to consume both first and second buff from sepsis

### ISSUE THREAD

**Issue by GarrettCottrell** [herotc/hero-rotation#991]
### What version of HeroRotation are you using?

10.1.7.10

### What version of HeroLib are you using?

10.1.7.03

### What version of HeroDBC are you using?

10.1.7.01

### What is the issue?

The addon seems to consistently recommend using ambush to consume the sepsis buff instead of garrote (with no blindside proc).  

I noticed this and then did a few bosses and watched how often I would get a recommendation of ambush vs. garrote after using sepsis and I was always recommended ambush. 

### Icon Behavior

None

**Comment by NStrategy** [comment]
The issue is not technically a bug. Assassination has not been updated to reflect the latest APL. This is the reason HeroRotation incorrectly recommends using Ambush to consume the Sepsis buff instead of Garrote. 
Since 10.2 is about to come out and Koji, the developer responsible for Rogue in HeroRotation, is probably busy with other stuff related to 10.2, you should not expect this to be fixed anytime soon. 
I have created a fork of HeroRotation that "fixes" this issue. If you're interested, you can contact me as "kekwxqcl" on Discord. This is just an alternative, offered with respect for the official version.

**Comment by GarrettCottrell** [comment]
Thanks for this - I can't seem to message you on discord though, is there another name or something I'm missing? I'd love to use the fork

**Comment by NStrategy** [comment]
Check your E-mail, I sent you a message.

**Comment by framara** [comment]
Hi @NStrategy, this [fork](https://github.com/NStrategy/hero-rotation)?

**Comment by NStrategy** [comment]
> Hi @NStrategy, this [fork](https://github.com/NStrategy/hero-rotation)?

Yes, for Assa to work you also need to download Rogue.lua (I added "LightweightShiv = Spell(394983)," there).

**Comment by framara** [comment]
Thanks I'm using your whole /rogue folder on the main repo and it works great. 
Also love your rupture skips on the raid too.
